default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>

development:
  <<: *default
  database: <%= ENV['MYSQL_DB_DEVELOPMENT'] || 'deploy_ecs_development' %>

test:
  <<: *default
  database: <%= ENV['MYSQL_DB_TEST'] || 'deploy_ecs_test' %>

production:
  <<: *default
  database: <%= ENV['MYSQL_DB_PRODUCTION'] || 'deploy_ecs' %>
